# Generated by Django 5.1.2 on 2024-10-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_application', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_application.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_application.user')),
            ],
        ),
    ]
